myhost: localhost
online: false

logging.config: classpath:log-dev.xml


server.port: 8081


spring:
  session:
    store-type: redis
  redis:
    host: ${myhost}
    port: 6379
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: admin

# io.dubbo.springboot.DubboProperties
spring.dubbo:
  # 扫描 @Service @Reference 注解所在的目录. 目录如果有多个用 <英文逗号(,)> 隔开
  scan: com.tudou
  application:
    # <dubbo:application name="c" id="c" />
    name: web-platform
    # <dubbo:registry address="zk://ip:port" timeout="10000" register="false" /> 只向注册中心订阅服务, 不注册
    registry:
      address: zookeeper://${myhost}:2181
      timeout: 10000
      register: false
    # 如果 zk 有集群, 去掉上面, 解开下面即可, 上面的方式只是基于一个 zk 实例
#    registries:
#      -
#        address: zookeeper://127.0.0.1:2181
#        timeout: 10000
#        register: false
#      -
#        address: zookeeper://127.0.0.2:2181
#        timeout: 1000
#        register: false

